# Generated by Django 5.0.3 on 2024-12-06 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhysicalAttributes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.PositiveIntegerField(help_text='Height in inches')),
                ('weight', models.PositiveIntegerField(help_text='Weight in lbs')),
                ('dash', models.DecimalField(decimal_places=2, help_text='Fastest 40-yard dash in seconds', max_digits=5)),
                ('bench_press', models.PositiveIntegerField(help_text='Bench press max in lbs')),
                ('deadlift', models.PositiveIntegerField(help_text='Deadlift max in lbs')),
                ('squat', models.PositiveIntegerField(help_text='Squat max in lbs')),
                ('wingspan', models.PositiveIntegerField(help_text='Wingspan in inches')),
                ('vertical_jump', models.PositiveIntegerField(help_text='Vertical jump height in inches')),
                ('heart_rate', models.PositiveIntegerField(help_text='Resting heart rate in bpm')),
                ('vo2_max', models.DecimalField(blank=True, decimal_places=2, help_text='VO2 Max if known', max_digits=5, null=True)),
                ('dominant_hand', models.CharField(choices=[('right', 'Right'), ('left', 'Left'), ('ambidextrous', 'Ambidextrous')], default='right', max_length=12)),
                ('eye_color', models.CharField(choices=[('brown', 'Brown'), ('blue', 'Blue'), ('green', 'Green'), ('hazel', 'Hazel'), ('gray', 'Gray'), ('amber', 'Amber')], default='brown', max_length=6)),
                ('hair_color', models.CharField(choices=[('black', 'Black'), ('brown', 'Brown'), ('blonde', 'Blonde'), ('red', 'Red'), ('gray', 'Gray'), ('white', 'White')], default='black', max_length=6)),
            ],
        ),
    ]
