# Generated by Django 5.0.3 on 2024-12-07 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_physicalattributes_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='physicalattributes',
            old_name='bench_press',
            new_name='bench_press_max',
        ),
        migrations.RenameField(
            model_name='physicalattributes',
            old_name='deadlift',
            new_name='deadlift_max',
        ),
        migrations.RenameField(
            model_name='physicalattributes',
            old_name='dash',
            new_name='fastest_40_yard_dash',
        ),
        migrations.RenameField(
            model_name='physicalattributes',
            old_name='heart_rate',
            new_name='resting_heart_rate',
        ),
        migrations.RenameField(
            model_name='physicalattributes',
            old_name='squat',
            new_name='squat_max',
        ),
        migrations.RenameField(
            model_name='physicalattributes',
            old_name='vertical_jump',
            new_name='vertical_jump_height',
        ),
    ]
