# Generated by Django 5.0.3 on 2024-12-09 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_bench_press_physicalattributes_bench_press_max_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physicalattributes',
            name='bench_press_max',
            field=models.PositiveIntegerField(blank=True, help_text='Bench press max in lbs', null=True),
        ),
        migrations.AlterField(
            model_name='physicalattributes',
            name='deadlift_max',
            field=models.PositiveIntegerField(blank=True, help_text='Deadlift max in lbs', null=True),
        ),
        migrations.AlterField(
            model_name='physicalattributes',
            name='fastest_40_yard_dash',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Fastest 40-yard dash in seconds', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='physicalattributes',
            name='height',
            field=models.PositiveIntegerField(blank=True, help_text='Height in inches', null=True),
        ),
        migrations.AlterField(
            model_name='physicalattributes',
            name='resting_heart_rate',
            field=models.PositiveIntegerField(blank=True, help_text='Resting heart rate in bpm', null=True),
        ),
        migrations.AlterField(
            model_name='physicalattributes',
            name='squat_max',
            field=models.PositiveIntegerField(blank=True, help_text='Squat max in lbs', null=True),
        ),
        migrations.AlterField(
            model_name='physicalattributes',
            name='vertical_jump_height',
            field=models.PositiveIntegerField(blank=True, help_text='Vertical jump height in inches', null=True),
        ),
        migrations.AlterField(
            model_name='physicalattributes',
            name='weight',
            field=models.PositiveIntegerField(blank=True, help_text='Weight in lbs', null=True),
        ),
        migrations.AlterField(
            model_name='physicalattributes',
            name='wingspan',
            field=models.PositiveIntegerField(blank=True, help_text='Wingspan in inches', null=True),
        ),
    ]
