# Generated by Django 5.0.3 on 2024-12-09 17:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_physicalattributes_bench_press_max_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='physicalattributes',
            name='dominant_hand',
            field=models.CharField(choices=[('no-selection', 'no-selection'), ('right', 'Right'), ('left', 'Left'), ('ambidextrous', 'Ambidextrous')], default='right', max_length=12),
        ),
        migrations.AlterField(
            model_name='physicalattributes',
            name='eye_color',
            field=models.CharField(choices=[('no-selection', 'no-selection'), ('brown', 'Brown'), ('blue', 'Blue'), ('green', 'Green'), ('hazel', 'Hazel'), ('gray', 'Gray'), ('amber', 'Amber')], default='brown', max_length=12),
        ),
        migrations.AlterField(
            model_name='physicalattributes',
            name='hair_color',
            field=models.CharField(choices=[('no-selection', 'no-selection'), ('black', 'Black'), ('brown', 'Brown'), ('blonde', 'Blonde'), ('red', 'Red'), ('gray', 'Gray'), ('white', 'White')], default='black', max_length=12),
        ),
        migrations.CreateModel(
            name='ICan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solve_rubiks_cube', models.BooleanField(default=False)),
                ('dunk_basketball', models.BooleanField(default=False)),
                ('do_a_backflip', models.BooleanField(default=False)),
                ('juggle_three_balls', models.BooleanField(default=False)),
                ('ride_a_unicycle', models.BooleanField(default=False)),
                ('do_a_cartwheel', models.BooleanField(default=False)),
                ('swim', models.BooleanField(default=False)),
                ('do_10_push_ups', models.BooleanField(default=False)),
                ('do_a_muscle_up', models.BooleanField(default=False)),
                ('touch_your_toes', models.BooleanField(default=False)),
                ('spin_a_basketball_on_your_finger', models.BooleanField(default=False)),
                ('drive_a_car', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ican', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
